run:
  timeout: 5m
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
linters:
  disable:
    - maligned
    - prealloc
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
