name: test


on:
  push:
    branches:
      - main
  pull_request:

jobs:
  mod:
    runs-on: ubuntu-latest
    name: Check modules
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: actions/checkout@v4
      - run: |
          for dir in $(find . -name go.mod -exec dirname {} \;); do
            cd $dir
            go mod tidy
            git diff --exit-code go.mod go.sum
            cd -
          done
  test:
    runs-on: ubuntu-latest
    name: Go test
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: actions/checkout@v4
      - uses: magefile/mage-action@v3
        with:
          args: test:ci .coverage-report.out test-report.json junit-report.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: .coverage-report.out
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
        if: "!cancelled()"
      - name: Test Summary
        uses: test-summary/action@v1
        with:
          paths: |
            junit-report.xml
        if: "!cancelled()"
